### ISSUE TITLE
Error when using decompile-apk.sh

### ISSUE THREAD

**Issue by alfikr** [venshine/decompile-apk#1]
this is the error message
 ./decompile-apk.sh: Syntax error: "(" unexpected

**Comment by venshine** [comment]
Copy the specific error message

**Comment by pdelteil** [comment]
Same problem here.

**Comment by OkancanCosar** [comment]
same problem

**Comment by iainheng** [comment]
I am having the same problem here. Tested with Ubuntu. 

![image](https://user-images.githubusercontent.com/3263759/44847485-3b94c200-ac86-11e8-8de6-e22e8219e965.png)

Confirmed shell is `bash`.

**Comment by sigaev-pro** [comment]
Same problem with `bash`

**Comment by message** [comment]
same

**Comment by omidraha** [comment]
same
